pipeline {
    agent any

    environment {
        VENV_DIR = 'venv'
        
    }

    stages {
        stage('Checkout') {
            steps {
                echo 'Cloning code...'
                checkout scm
            }
        }

        stage('Setup Python Environment') {
            steps {
                echo 'Setting up virtual environment...'
                sh '''
                    python3 -m venv $VENV_DIR
                    . $VENV_DIR/bin/activate
                    pip install --upgrade pip
                    pip install -r requirements.txt
                '''
            }
        }

        stage('Run Tests with Pytest') {
            steps {
                echo 'Running tests...'
                sh '''
                    . $VENV_DIR/bin/activate
                    pytest tests/
                '''
            }
        }

        stage('Code Coverage Report') {
            steps {
                echo 'Generating coverage report...'
                sh '''
                    . $VENV_DIR/bin/activate
                    coverage run -m pytest tests/
                    coverage report
                    coverage html
                '''
            }
        }
    }

    post {
        always {
            echo 'Cleaning up...'
            sh 'rm -rf $VENV_DIR'
        }
    }
}
